### ISSUE TITLE
标题能自动编号吗？

### ISSUE THREAD

**Issue by maxchendt** [xtfly/hugo-theme-next#1]
不好意思，用这种方式打扰您，看了 [Hexo NexT主题移植](http://lanlingzi.cn/post/technical/2016/0828_hugo_next_theme/)，能否实现标题自动编号？最好是在Hexo 的 next 主题下实现。

我参考 https://github.com/3meng/3meng.github.io/issues/1  实现了 hexo landscape 下的自动编号，但不知道 next 主题下如何修改

先谢谢了！

**Comment by maxchendt** [comment]
打扰了，搞定了， https://github.com/iissnan/hexo-theme-next/issues/1112

**Comment by xtfly** [comment]
@maxchendt 多谢您的关注。在您提供解决办法基础之上，我也在侧边的TOC列表上自动加上序列了。

https://github.com/xtfly/hugo-theme-next/blob/master/static/js/toc.js

```
 function toc(parent, prefex) {
    parent.children("ul").each(function () {
      $ul = $(this);
      $ul.children("li").each(function () {
        $li = $(this);
        listStr = prefex
        if ($li.children("a").length > 0) {
          if (listStr != "") { listStr += "."}
          listStr += ($li.index() + 1);
          $li.html(listStr + " " + $li.html());
          toc($li, listStr)
        } else {
          toc($li, listStr)
        }
      });
    });
  }

var $t = $("#TableOfContents");
toc($t, "");
```

**Comment by maxchendt** [comment]
再打扰下， https://github.com/iissnan/hexo-theme-next/issues/680#issuecomment-245922396 里面让部分段落不缩进，有什么想法否？

**Comment by maxchendt** [comment]
搞定！特定段落不缩进，在该段落进行标记

``` javascript
<script type="text/javascript">
$('p:contains("ooNoIndent00")').each(function() {
    var text = $(this).html();
    $(this).css('text-indent', '0em');
    $(this).html(text.replace('ooNoIndent00', '')); 

});
</script>
```

**Comment by github-young** [comment]
awsl，发现我的标题都被双重标号了，原来是这个issue...应该有个选项可以选择是否自动标号。我现在的做法就是把`` theme/next/static/js/toc.js ``删了
