### ISSUE TITLE
search.js not working when baseUrl contains child path. 当baseUrl不是根域名(.io)时搜索功能失效

### ISSUE THREAD

**Issue by github-young** [xtfly/hugo-theme-next#14]
As I mentioned in [this issue](https://github.com/github-young/hugo-theme-next/issues/1), I find that the search function is not working if the `` baseUrl `` contains a child path instead of a simple `` .io `` URL. Since I know nothing about JavaScript, I hope you could help me. Thank you.

我根据您的项目移植了Next主题的Gemini方案，用作demo的地址是 `` https://github-young.github.io/hugo-theme-next/ ``，但是我发现侧边栏的搜索功能没有用，经过排查和检验，发现只有baseUrl为根域名时（比如 https://xxx.github.io/ ）才有用。我不知道怎么解决，希望您有时间可以看以下。谢谢。

**Comment by xtfly** [comment]
@github-young
请修改js/search.js文件中，把path值加上你的子路径
```
    var search_path = "sitemap.xml";
    var path = "/" + search_path;
```

**Comment by github-young** [comment]
> @github-young
> 请修改js/search.js文件中，把path值加上你的子路径
> 
> ```
>     var search_path = "sitemap.xml";
>     var path = "/" + search_path;
> ```

谢谢，解决了
