### ISSUE TITLE
 Unable to find archetypes directory for theme "next" 

### ISSUE THREAD

**Issue by choicky** [xtfly/hugo-theme-next#2]
这主题挺漂亮的。

我新装的hugo，创建文件时提示  Unable to find archetypes directory for theme "next"  ，是不是github的theme版本文件不全？

**Comment by akkuman** [comment]
自己在主题文件夹下面新建文件夹archetypes，然后里面放入模板，具体怎么做可以查看官方文档

**Comment by xtfly** [comment]
@akkuman  多谢解答，好久没有上github了。

**Comment by xtfly** [comment]
已增加archetypes，以及模板
https://github.com/xtfly/hugo-theme-next/blob/master/archetypes/default.md
